# Generated by Django 6.0 on 2025-12-25 15:57

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
