# Generated by Django 6.0 on 2025-12-25 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_product_fecha_creacion_alter_product_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cliente',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas/'),
        ),
        migrations.AddField(
            model_name='lana',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lana',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lanas/'),
        ),
    ]
