# Generated by Django 6.0 on 2025-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_remove_product_cliente_herramienta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
